env:
  global:
    secure: "I5J7jKbj3ociXgYTkz03g2/5dmQdiqBZ1xqKYAvvLyRDYd1JqH00JO71IX+lfhDflx4aFgZmVz/pcG77YQYv/LJ358z13YzTkS22takBafEVDPqvQln4nvLVUCSoriKfeL/D0iGJGuyNmhO696DCMSsV82/td8NjLD0o0cwoqt7j/mOZGmESDt/BsgQ+oeW+FsbNARTEuQtY7qqz6F9lMINloQY0qhx0dQP6nl5VhAyQDq5e5a31xygSUkAClvbcN0puU+5oU+WeuhsqmKJ4RFgklhgUJxQ60bN5vD6eOW2G6LIX7oOJZoP/HJJElP4YTaPgg2Mxlogco/hvQEmFdOzJghQxkduKp1+fSA+3n22jmMw7nhIH92FoPvJQppKcQyuAKkpRPWQyitXlPPX5rby6hBxpYRb6awgf2vCKIAeeCgsB9C9/QAHdUPc99+6CKRhAY9VHFIzCaOKaegXJjudlMV5VQ/SsbWiceHBl2gvmnaIpOUf4n4tewKJKspXN9k+T3ICr5EOA4+ksQhMxSmW7IMwgmx2Ykg+lLObhENdFHrcFcSmOhAWxRhgJkNim2aiOrvxanaBDRKVote4dwEmlYlLAdpfD/T4sgMeowKsXALrgYpUnVTZL9U40QuGZFrPygtVZSjQmBkdgVtemKnshwpufxPJ015c5rYzVkTI="

script:
  - echo VAL1 = $VAL1
  - echo VAL2 = $VAL2
  - echo VAL3 = $VAL3
